imports = [
    "assets/assets-1x.toml",
    "assets/assets-2x.toml",
]

[font.virtual-boy]
file = "assets/virtual-boy.ttf"
size = 32

[image.menu-item]
chardata = "all"
file = "assets/menu.png"
position = [0, 0]
size = [64, 64]

[image.menu-item-selected]
chardata = "all"
file = "assets/menu.png"
position = [64, 0]
size = [64, 64]
