imports = [
    "assets/assets-1x.toml",
    "assets/assets-2x.toml",
    "assets/assets-megu.toml"
]

[font.virtual-boy]
file = "assets/virtual-boy.ttf"
size = 32

[font.menu]
file = "assets/yoster.ttf"
size = 14

[image.menu-item]
chardata = "all"
file = "assets/menu.png"
position = [0, 0]
size = [56, 56]

[image.menu-item-selected]
chardata = "all"
file = "assets/menu.png"
position = [56, 0]
size = [56, 56]

[image.pause]
chardata = "all"
file = "assets/pause.png"

[image.menu-arrow-right]
chardata = "all"
file = "assets/menu-arrow.png"

[image.menu-arrow-left]
chardata = "all"
hflip = true
file = "assets/menu-arrow.png"

[image.title-left]
chardata = "title"
file = "assets/title.png"
position = [0, 0]
size = [384, 224]

[image.title-right]
chardata = "title"
file = "assets/title.png"
position = [0, 224]
size = [384, 224]

[image.start]
chardata = "title"
file = "assets/start.png"
